apiVersion: apps/v1
kind: Deployment
metadata: {name: booking-service, namespace: proconnect}
spec:
  replicas: 1
  selector: {matchLabels: {app: booking-service}}
  template:
    metadata: {labels: {app: booking-service}}
    spec:
      containers:
      - name: booking-service
        image: your-registry/booking-service:latest
        ports: [{containerPort: 4003}]
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:postgres@postgres.proconnect.svc.cluster.local:5432/booking_db"
        - name: AUTH_URL
          value: "http://auth-service.proconnect.svc.cluster.local:4001"
        - name: CORS_ORIGIN
          value: "*"
---
apiVersion: v1
kind: Service
metadata: {name: booking-service, namespace: proconnect}
spec:
  selector: {app: booking-service}
  ports: [{port: 4003, targetPort: 4003}]
